[custom]

;精简分流规则
;特点：简洁实用、地区分组自动测速、AI专用分组、便于长期维护

ruleset=🇸🇬 新加坡,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
; 局域网直连
ruleset=🎯 国内流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml

; 广告拦截 
ruleset=🛑 广告拦截,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.yaml

ruleset=🇸🇬 新加坡,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml

; 补充
ruleset=DIRECT,clash-classic:https://raw.githubusercontent.com/alva-cui/ClashRule/main/Rule/Replenish.yaml

; AI服务
ruleset=🧚 AI服务,clash-classic:https://raw.githubusercontent.com/cutethotw/ClashRule/refs/heads/main/Rule/AI.yaml
ruleset=🧚 AI服务,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml
ruleset=🧚 AI服务,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml
ruleset=🧚 AI服务,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
ruleset=🧚 AI服务,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml

; 国外流量
ruleset=🚀 国外流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml
ruleset=🚀 国外流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Discord/Discord.yaml
ruleset=🚀 国外流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml

; 国内直连 
ruleset=🎯 国内流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml
ruleset=🎯 国内流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Classical_No_IPv6.yaml
ruleset=🎯 国内流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin.yaml
ruleset=🎯 国内流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Youku/Youku.yaml
ruleset=🎯 国内流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apifox/Apifox.yaml
ruleset=🎯 国内流量,[]GEOIP,CN

; 国外流量
ruleset=🚀 国外流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Classical.yaml
ruleset=🚀 国外流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml

; 漏网之鱼 
ruleset=🐟 漏网之鱼,[]FINAL

; AI 服务 
custom_proxy_group=🤖 AI自动`fallback`(美|US|新加坡|SG|狮城|Gemini|GPT)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🧚 AI服务`select`[]🤖 AI自动`[]🇺🇸 美国节点`[]🇸🇬 新加坡`[]✈️ 手动选择

; 业务分组 
custom_proxy_group=🚀 国外流量`select`[]♻️ 自动选择`[]🔯 故障转移`[]✈️ 手动选择
custom_proxy_group=🎯 国内流量`select`[]DIRECT`[]♻️ 自动选择`[]✈️ 手动选择`[]🇨🇳 回国节点
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 国外流量`[]DIRECT`[]✈️ 手动选择

; 基础分组 
custom_proxy_group=✈️ 手动选择`select`[]♻️ 自动选择`.*
custom_proxy_group=♻️ 自动选择`url-test`(^(?!.*(电信|联通|移动|剩余|流量|官网|客服|套餐|到期)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 故障转移`fallback`(^(?!.*(电信|联通|移动|剩余|流量|官网|客服|套餐|到期)).*)`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT

; 地区分组
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国节点`url-test`(美|US|United States)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡`url-test`(新加坡|SG|shiche|狮城)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌍 其他`url-test`^(?!.*(港|HK|Hong Kong|HongKong|美|US|USA|新加坡|SG|狮城)).*$`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
